name = "LFRBenchmarkGraphs"
uuid = "e2d0dd93-c6be-4a4f-9a61-2b35d7242bb2"
authors = ["Dimitris Floros <flojim4@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
