name = "LFRBenchmarkGraphs"
uuid = "e2d0dd93-c6be-4a4f-9a61-2b35d7242bb2"
authors = ["Dimitris Floros"]
version = "1.0.0"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
lfr_benchmark_jll = "cb590574-ea86-51dd-800e-297a027516d0"

[compat]
julia = "1.6"
Graphs = "1"
lfr_benchmark_jll = "1.0"
